name: Deploy Streamlit to EC2

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}

        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem ${USER}@${HOSTNAME} << 'EOF'
            cd ~/custom_agent

            echo "→ Activando entorno virtual"
            source .venv/bin/activate

            echo "→ Haciendo pull del último código"
            git pull origin main

            echo "→ Instalando dependencias"
            pip install -r requirements.txt

            echo "→ Deteniendo instancia de Streamlit en tmux si existe"
            tmux kill-session -t streamlit_session || true

            echo "→ Ejecutando app en sesión tmux"
            tmux new-session -d -s streamlit_session 'source .venv/bin/activate && streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true'
          EOF
